devs/developers/developers/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls')),
]

admin.site.site_header = 'Devs Administration'                    # default: "Django Administration"
admin.site.index_title = 'Developers'                 # default: "Site administration"
admin.site.site_title = 'Developers site admin' # default: "Django site admin"

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

devs/developers/users/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.profiles, name="profiles"),
    path("user-profile/<str:pk>", views.user_profile, name="user-profile"),
    path('user-login/', views.userLogin, name='user-login'),
    path('user-register/', views.userRegister, name='user-register'),
    path('user-logout/', views.userLogout, name='user-logout'),
    path('update-profile/', views.updateProfile, name='update-profile'),
    path('user-account/', views.userAccount, name='user-account'),
    path('msgs/', views.userMsgs, name='msgs'),
    path('read-msg/', views.read_msg, name='read-msg'),
    path('msg-details/', views.getMsgDetails, name='msg-details'),
    path('send-reply/', views.sendReply, name="send-reply")
]

devs/developers/users/models.py
from django.db import models
from django.contrib.auth.models import User
import uuid

class Profile(models.Model):
    userid = models.UUIDField(default=uuid.uuid4, unique=True, primary_key=True, editable=False)
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True, blank=True)
    email = models.EmailField(max_length=500, blank=True, null=True)
    username = models.CharField(max_length=200, blank=True, null=True)
    first_name = models.CharField(max_length=200, blank=True, null=True)
    last_name = models.CharField(max_length=200, blank=True, null=True)
    location = models.CharField(max_length=200, blank=True, null=True)
    short_intro = models.CharField(max_length=200, blank=True, null=True)
    bio = models.TextField(blank=True, null=True)
    profile_image = models.ImageField(null=True, blank=True, upload_to='profiles/', default="profiles/user-default.png")
    social_github = models.CharField(max_length=200, blank=True, null=True)
    social_twitter = models.CharField(max_length=200, blank=True, null=True)
    social_linkedIn = models.CharField(max_length=200, blank=True, null=True)
    social_youtude = models.CharField(max_length=200, blank=True, null=True)
    social_website = models.CharField(max_length=200, blank=True, null=True)
    created = models.DateTimeField(auto_now_add=True)
    
    
    def __str__(self) -> str:
        return str(self.username)
    
    class Meta:
        ordering = ['-created']

class Skill(models.Model):
    owner = models.ForeignKey(Profile, on_delete=models.CASCADE, null=True, blank=True)
    name = models.CharField(max_length=200, blank=True, null=True)
    description = models.TextField(blank=True, null=True)
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4, unique=True, primary_key=True, editable=False)
    
    def __str__(self) -> str:
        return str(self.name)


class Message(models.Model):
    sender = models.ForeignKey(Profile, on_delete=models.SET_NULL, null=True, blank=True, related_name="sent_messgaes")
    recipient = models.ForeignKey(Profile, on_delete=models.SET_NULL, null=True, blank=True, related_name="received_messages")
    name = models.CharField(max_length=200, null= True, blank=True)
    email = models.EmailField(max_length=200, null= True, blank=True)
    subject = models.CharField(max_length=200, null= True, blank=True)
    body = models.TextField()
    is_read = models.BooleanField(default=False,null=True)
    created = models.DateTimeField(auto_now_add=True)
    parent = models.ForeignKey('self', null=True, blank=True, related_name="replies", on_delete=models.CASCADE)
    id=models.UUIDField(default=uuid.uuid4, unique=True, primary_key=True,editable=False)
    
    def __str__(self) -> str:
        return str(self.subject)
    
    class Meta:
        ordering = ['is_read', '-created']

devs/developers/users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.forms import ModelForm
from .models import Profile, Message

class RegistrationForm(UserCreationForm):
    email = forms.EmailField(required=True, max_length=500)
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'username', 'email', 'password1', 'password2',)
        
        
class ProfileForm(ModelForm):
    class Meta:
        model = Profile
        fields = '__all__'
        exclude = ['user','created_date']


class MessageForm(ModelForm):
    class Meta:
        model = Message
        fields = ('name', 'email', 'subject', 'body')
        

class ReplyForm(ModelForm):
    class Meta:
        model=Message
        fields = ['body']

    def clean_body(self): 
        body = self.cleaned_data.get('body') 
        # Example: Strip leading and trailing whitespace 
        body = body.strip() # Add additional sanitization/validation as needed 
        if len(body) > 1000: # Example constraint 
            raise forms.ValidationError("Reply content is too long.") 
        return body

devs/developers/users/views.py
from django.shortcuts import render, redirect
from .models import Profile, Message
from .forms import RegistrationForm
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.decorators import login_required
from django.views.decorators.cache import cache_control
from django.contrib.auth.models import User
from .utils import searchProfiles
from extras import paginateObject
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from .forms import ProfileForm, MessageForm, ReplyForm
from django.views.decorators.http import require_POST, require_GET
from django.http import JsonResponse
from django.core.mail import EmailMessage, get_connection
from django.conf import settings



def profiles(request):
    profiles, search_query = searchProfiles(request)
    
    custom_range, profiles = paginateObject(request, profiles)
    
    context={
        'search_query':search_query, 
        'profiles':profiles,
        'custom_range':custom_range
    }
    return render(request, 'users/profiles.html', context)

def user_profile(request, pk):
    profile = Profile.objects.get(userid=pk)

    form = MessageForm()

    if request.user.is_anonymous:
        sender = None
    else:
        try:
            sender = request.user.profile 
        except User.DoesNotExist:
            sender = None
    #print(f'User is : {sender}')
    
    if request.method == "POST":
        form =MessageForm(request.POST)
        if form.is_valid():

            message = form.save(commit=False)
            message.name = form.cleaned_data['name']
            message.email = form.cleaned_data['email']
            message.subject = form.cleaned_data['subject']
            message.body = form.cleaned_data['body']

            # When user is not authenticated.
            message.sender = sender
            message.recipient = profile

            # When user is authenticated 
            if sender:
                message.name = sender.first_name +' '+ sender.last_name
                message.email = sender.email
            
            message.save()

    context = {
        'profile':profile,
        'form':form
        }
    return render(request, 'users/user-profile.html', context)


@cache_control(no_cache=True, must_revalidate=True, no_store=True)
def userRegister(request):
    page = "register"
    
    form = RegistrationForm()
    if request.user.is_authenticated:
        return redirect('profiles')
    elif request.method == 'GET':
        form = RegistrationForm()
    elif request.method=='POST':
        print(request.POST)
        form = RegistrationForm(request.POST)
        if form.is_valid():
            user=form.save()
            login(request, user)
            return redirect('profiles')
        else:
            form = RegistrationForm()
    else:
        form = RegistrationForm()
    context = {
        'page':page,
        'form':form,
    }
    return render(request, 'users/login_register.html', context)
            


@cache_control(no_cache=True, must_revalidate=True, no_store=True)
def userLogin(request):
    page = "login"
    
    if request.user.is_authenticated:
        return redirect('profiles')
    
    if request.method == 'POST':
        username = request.POST['username'].lower()
        password = request.POST['password']
        
        
        try:
            user = User.objects.get(username=username)
            
        except:
            print(f'The user username {username} does not exits.')
        
        user = authenticate(username=username, password=password)
        
        if user is not None:
            login(request, user)
            return redirect('profiles')
        
        
    
    context = {
        'page':page,
    }
    return render(request, 'users/login_register.html', context)


def userLogout(request):
    logout(request)
    return redirect('user-login')   

@login_required(login_url="user-login")
def userAccount(request):
    profile = request.user.profile
    
    context = {'profile':profile}
    return render(request, 'users/user-account.html', context)


@login_required(login_url='user-login')
def updateProfile(request):
    profile = request.user.profile
    form = ProfileForm(instance=profile)
    
    if request.method == 'POST':
        form = ProfileForm(request.POST, request.FILES, instance=profile)
        if form.is_valid():
            form.save()
            return redirect('profiles')
    
    context = {
        'form':form,
    }
    return render(request, 'users/update_profile.html', context)
    
@login_required(login_url='user-login')
def userMsgs(request):
    profile = request.user.profile
    msgsRecipient = Message.objects.filter(recipient=profile)
    msgsSender = Message.objects.filter(sender=profile)
    unreadCount = msgsRecipient.filter(is_read=False).count()
    
    form = MessageForm()
    if request.method == 'POST':
        form = MessageForm(request.POST)
        if form.is_valid():
            form.save(commit=False)
            msgsRecipient.sender = request.user
            form.save()
            return redirect('msgs')
        else:
            form = MessageForm()
   
    #Send Emails

    #send_emails(request)

    context ={
        'msgsRecipient':msgsRecipient,
        'msgsSender':msgsSender,
        'unreadCount':unreadCount, 
    }
    return render(request, 'users/messages.html', context)


@login_required(login_url='user-login')
@require_POST
def read_msg(request):
    import json
    profile = request.user.profile
    data = json.loads(request.body)
    msgid = data.get('msgid')
    #print(f'This, {msgid}, should not be empty.')
    #print(f'Parsed data {data}, Type: {type(data)}')
    if msgid:
        try:
            msg = Message.objects.get(id=msgid)
            msg.is_read = True
            msg.save()
            unreadCount = Message.objects.filter(recipient=profile, is_read=False).count()
            #print(f'Returning response with unreadCount {unreadCount}')
            return JsonResponse({
                'status':'success',
                'unreadCount' : unreadCount
            })
        except Message.DoesNotExist:
            return JsonResponse({
                'status':'error',
                'message':'Message not found'
            }) 
    return JsonResponse({
                'status':'error',
                'message':'Invalid request'
            })
          

@require_GET
def getMsgDetails(request):
    #import json
    #data = json.loads(request.body)
    #msgid = data.get('msgid')
    msgid = request.GET.get('msgid')
    if msgid:
        try:
            msg = Message.objects.get(id=msgid)
            return JsonResponse({
                'subject': msg.subject,
                'senderEmail': msg.email,
                'senderName':msg.name,
                'recipientName':msg.recipient.first_name +' '+ msg.recipient.last_name,
                'recipientEmail': msg.recipient.email,
                'body': msg.body,
                'created' : msg.created.strftime('%Y-%m-%d, %H:%M:%S'),
                'picture' : msg.sender.profile_image.url if msg.sender else 'profiles/user-default.png'
            })
        except Message.DoesNotExist:
            return JsonResponse({
                'status':'error',
                'message':'Message not found'
            }) 
    return JsonResponse({
                'status':'error',
                'message':'Invalid request'
            })

@require_POST
def sendReply(request):
    if request.method == 'POST':
        import json
        data = json.loads(request.body)
        reply_body = data.get('replyContent')
        
        msgid = data.get('msgid')
        print(f'id = {msgid}')
        try:
            parent_message = Message.objects.get(id=msgid)
            recipientEmail = parent_message.email
            user = User.objects.get(email=recipientEmail)
            #print(f'parent: {parent_message},  id= {msid}')
            form = ReplyForm({'body': reply_body})

            if form.is_valid():
                reply_msg = form.save(commit=False)
                reply_msg.sender = request.user.profile
                reply_msg.recipient = parent_message.sender
                reply_msg.subject = f'Re: {parent_message.subject}'
                reply_msg.body = form.cleaned_data['body']
                reply_msg.parent = parent_message
                reply_msg.save()

                return JsonResponse({
                    'status': 'success',
                    'reply_id': reply_msg.id
                })
            else:
                return JsonResponse({
                    'status':'errors',
                    'message':'Invalid data',
                    'errors':form.errors
                }, status=400)
        except User.DoesNotExist:
            #Send reply to non users. 
            print('User does not exist.')
        except Message.DoesNotExist:
            return JsonResponse({
                'status':'error',
                'message':'Message not found'
            }, status=400)
    return JsonResponse({
                'status':'error',
                'message':'Invalid method'
            }, status=400)

devs/developers/users/templates/users/login_register.html
{% extends "base.html" %}
{% load widget_tweaks %}
{% block content %}

{% if page == "login" %}
<section class="user-login-reg"> 
    <div class="container container-login-reg" >
      <div class="log-user" >
            <div class="row g-4" >
              <div class="col-lg-4 bg-success p-4 d-none d-lg-block reg-img">
                
              </div>
             
              <div class="col-lg-8 p-5 border border-2 rounded-4">
                <form action="" method="POST">
                  {% csrf_token %}                                                   
                  <div class="float mb-4">
                    <input type = "text" class="form-control" placeholder = "Enter your username" name = "username" autocomplete = "off"/>
                    <label for = "id_username">Username</label>
                    <!-- Rendering field errors -->
                  </div>
                  <div class="float mb-3">
                    <input type = "password" class="form-control" placeholder = "Enter your password" name = "password" autocomplete = "off"/>
                    <label for = "id_password">Password</label>
                    <!-- Rendering field errors -->
                  </div>
                  <div class="d-flex justify-content-end mb-5">
                    <span><a href="#">Forgot password?</a></span>
                  </div>        
                  <div class="d-grid p-1">
                      <button  type="submit"  class="btn btn-primary  btn-block">Login</button>
                  </div>
                </form>

                <div class="d-flex justify-content-center pt-4">
                  <p class="p-2">Don't have an account?  </p><span class="p-2"><a href="{% url 'user-register' %}">Create account</a></span>
                </div>
                  
              </div>
              
            </div>
          
      </div>
  </div>
  
</section>
{% endif %}

{% if page == "register" %}
<section class="user-login-reg">
  <div class="container container-login-reg">
    <div class="reg-user">
        <form action="" method="POST">
          {% csrf_token %}
          <div class="row g-4">
            <div class="col-lg-4 bg-success p-4 d-none d-lg-block reg-img">
              
            </div>
            <div class="col-lg-8 p-4 border border-2 rounded-4">
               
                <div class="row">
                    <div class="col-lg-6">
                      <div class="float mb-4">
                        {% render_field form.first_name class="form-control" placeholder=form.text.label%}
                        <label for="id_{{form.first_name.label|cut:' '}}">{{form.first_name.label}}</label>
                        <!-- Rendering field errors -->
                        {% for error in form.phone.errors %}
                        <span class="text-danger">{{ error }}</span>
                        {% endfor %}
                      </div>
                    </div>
                    <div class="col-lg-6">
                      <div class="float mb-4">
                        {% render_field form.last_name class="form-control" placeholder=form.text.label%}
                        <label for="id_{{form.last_name.label|cut:' '}}">{{form.last_name.label}}</label>
                        <!-- Rendering field errors -->
                        {% for error in form.phone.errors %}
                        <span class="text-danger">{{ error }}</span>
                        {% endfor %}
                      </div>
                    </div>
                </div>
                <div class="float mb-4">
                  {% render_field form.email class="form-control" placeholder=form.text.label %}
                  <label for="id_{{form.email.label|cut:' '}}">{{form.email.label}}</label>
                  <!-- Rendering field errors -->
                  {% for error in form.phone.errors %}
                  <span class="text-danger">{{ error }}</span>
                  {% endfor %}
                </div>

                <div class="float mb-4">
                  {% render_field form.username class="form-control" placeholder=form.text.label %}
                  <label for="id_{{form.username.label|cut:' '}}">{{form.username.label}}</label>
                  <!-- Rendering field errors -->
                  {% for error in form.phone.errors %}
                  <span class="text-danger">{{error}}</span>
                  {% endfor %}
                </div>
        
                <div class="float mb-4">
                  {% render_field form.password1 class="form-control" placeholder=form.text.label %}
                  <label for="id_{{form.password1.label|cut:" "}}">{{form.password1.label}}</label>
                  <!-- Rendering field errors -->
                  {% for error in form.phone.errors %}
                  <span class="text-danger">{{ error }}</span>
                  {% endfor %}
                </div>
        
                <div class="float mb-4">
                  {% render_field form.password2 class="form-control" placeholder=form.text.label %}
                  <label for="id_{{form.password2.label|cut:' '}}">{{form.password2.label}}</label>
                  <!-- Rendering field errors -->
                  {% for error in form.phone.errors %}
                  <span class="text-danger">{{ error }}</span>
                  {% endfor %}
                </div>        
                <div class="d-flex justify-content-center pt-3">
                  <button  type="button"  class="btn btn-light btn-lg">Reset all</button>
                  <button  type="submit"  class="btn btn-primary btn-lg ms-2">Create account</button>
                </div>

                <div class="d-flex justify-content-center pt-4">
                    <p class="p-2">Already have an account? </p><span class="p-2"><a href="{% url "user-login" %}">Login here</a></span>
                </div>
        
            </div>
          </div>

        </form>
  </div>
</div>
</section>
{% endif %}
{% endblock content %}

devs/developers/users/templates/users/messages.html
{% extends "base.html" %}
{% load widget_tweaks %}
{% block content %}
{% load humanize %}
<div class="container-fluid mt-1">
  
  <div class="row remain">
    <div class="col-lg-2 d-none d-lg-block shadow-lg p-2" >
      {% include "users/sidebar.html" %}
    </div>
    <div class="col-lg-10 bg-light">
      {% include "users/off_canvas.html" %}
      {% include "users/modal_msg.html" %}

      <div class="row d-lg-none d-block"> 
        <ul class="nav-sidebar">
          <li class="btn-left"><a class="btn btn-lg shadow border border-1 rounded" data-bs-toggle="offcanvas" href="#sideBarOffcanvas"><i class="fa fa-bars fa-lg" aria-hidden="true"></i> </a></li>
          <li class="btn-right"><a class="btn btn-lg  shadow border border-1 rounded" data-bs-toggle="modal" href="#myModal"><i class="fa fa-pencil fa-lg" aria-hidden="true"></i></a></li>
        </ul>
      </div>

      <div class="w3-container person p-3">
        <div id="msg-content" class="msg-content">
          <div class="row w-100 shadow-sm border border-2 rounded mb-2 bg-white" style="text-align:center;">
            <h6 id="msg-subject" class="mt-2 text-primary-emphasis"></h6>
          </div>

          <div class = "row shadow-sm border border-2 rounded mb-2 bg-white w-100">
            <div class="col-6 d-flex justify-content-start">
                <img id="pic-content" class="rounded mt-3" src="" style="width:10%; height:15%; ">
                <div class="">
                  <p><h6><span id="msg-sender-name"></span> <span id="msg-sender-email"></span></h6></p>
                  <p><h6 class="mb-2"><i class="fa fa-clock-o"></i> <span id="msg-sender-created"></span> </h6></p>
                </div>
             
            </div>
            <div class="col-6 bg-white d-flex justify-content-end">
              <div class="row mb-4">
                <div class="col-6">
                  <a class="btn btn-sm ms-1  btn-reply"  id="btn-reply" href="#">Reply<i class=" ms-2 fa fa-mail-reply"></i></a>
                </div>
                <div class="col-6">
                  <a class="btn btn-sm ms-4 " href="#">Forward<i class="ms-2 fa fa-arrow-right"></i></a>
                </div>
              </div>
            </div>
          </div> 
          <div class="row h-100 bg-white" >
            <span id="msg-recipient-name"></span> <span id="msg-recipient-email" data-recipient-email=""></span></h6>
            <hr>
            <div><p id="msg-body"></p></div>
            <div>
              <a class="btn btn-sm ms-1 shadow border border-1 rounded  btn-reply"  id="btn-reply" href="#">Reply<i class=" ms-2 fa fa-mail-reply"></i></a>
              <a class="btn btn-sm ms-4 shadow border border-1 rounded " href="#">Forward<i class="ms-2 fa fa-arrow-right"></i></a>
              <h6 class="mb-2"><span id="msg-sender-created"></span></h6></div>
            </div>
          </div>           
        </div>
        <div id = "reply-form-modal" class="border border-2 rounded shadow-sm p-3 bg-white" data-id="" style="display:none;"> 
          <form action="#" method="POST">
            {% csrf_token %}
            <div class="form-group mb-2">                    
              <label for="reply-text" class="form-label mt-2">Reply message</label>
              <textarea id="reply-text" class="form-control" rows="3" style="height: 162px;" placeholder="Type your reply here..."></textarea>                
            </div> 
            <div class="form-group">                    
              <button id = "send-reply">Send <i class=" ms-2 fa fa-mail-reply"></i></button>                
            </div> 
          </form>
        </div>
      </div> 
    </div>
  </div>
</div>
{% endblock content %}

devs/developers/users/templates/users/modal_msg.html
 <!-- The Modal -->
 {% load widget_tweaks %}
<div class="modal" id="myModal">
    <div class="modal-dialog modal-dialog-centered modal-lg">
      <div class="modal-content">
  
        <!-- Modal Header -->
        <div class="modal-header">
          <h4 class="modal-title">Message</h4>
          <button type="button" class="btn-close" data-bs-dismiss="modal"></button>
        </div>
  
       <form action="#" method="POST">
        {% csrf_token %}
         <!-- Modal body -->
          <div class="modal-body p-5">
            {% comment %} <div class="mb-4">
              <select name="recipient" class="form-select" id="id_recipient" required>
                <option value="" disabled selected>Select a recipient</option>
                {% for user in form.recipient.field.queryset %}
                <option value="{{user.id}}">{{user.username}}</option>
                {% endfor %}
              </select>
            </div>  {% endcomment %} 
            {% if request.user.is_authenticated == False %}
            <div class="float mb-5">
              {% render_field form.name class="form-control" placeholder="Enter you name" name="name"%}
              <label for="id_{{form.name.label|cut:' '}}">Name</label>
              <!-- Rendering field errors -->
              {% for error in form.name.errors %}
              <span class="text-danger">{{error}}</span>
              {% endfor %}
            </div>

            <div class="float mb-5">
              {% render_field form.email class="form-control" placeholder="Enter your email" name="from_email"%}
              <label for="id_{{form.email.label|cut:' '}}">Email</label>
              <!-- Rendering field errors -->
              {% for error in form.email.errors %}
              <span class="text-danger">{{error}}</span>
              {% endfor %}
            </div>
            {% endif %}
            
            
            
            <div class="float mb-5">
              {% render_field form.subject class="form-control" placeholder=form.text.label name="subject"%}
              <label for="id_{{form.subject.label|cut:' '}}">{{form.subject.label}}</label>
              <!-- Rendering field errors -->
              {% for error in form.subject.errors %}
              <span class="text-danger">{{error}}</span>
              {% endfor %}
            </div>
            <div class="float mb-2">
              {% render_field form.body class="form-control" name="body" %}
              <label for="id_{{form.body.label | cut:' '}}"></label>
              <!-- Rendering field errors -->
            </div>                               
          </div>
  
        <!-- Modal footer -->
        <div class="modal-footer">
          <div class="row w-100">
            <div class="col-3 form-group">                    
              <button type="button" class="btn btn-danger p-2" data-bs-dismiss="modal">Cancel</button>                
            </div> 
            <div class="col-9 form-group ">                    
              <button type="submit" class="btn float-end btn-dark p-2" for="form-group-input"> Send <i class="fa fa-paper-plane"></i></button>                
            </div> 
          </div>          
        </div>
       </form>
  
      </div>
    </div>
</div>
  

devs/developers/users/templates/users/off_canvas.html
<div class="offcanvas offcanvas-start" id="sideBarOffcanvas" style="overflow:auto">
    <div class="offcanvas-header">
      <h1 class="offcanvas-title">Heading</h1>
      <button id = "offcanvCloseBtn" type="button" class="btn-close text-reset"  data-bs-dismiss="offcanvas"></button>
    </div>
    <div class="offcanvas-body">
      {% include "users/sidebar.html" %}
    </div>
</div>

devs/developers/users/templates/users/profiles.html
{% extends "base.html" %}
{% block content %}
<main class="profiles">
    <div class = "container-fluid mb-4 bg-light">
        <h1 class="text-center p-5">Developers</h1> 
        {% if request.user.is_authenticated %}
            <strong>Welcome back {{request.user.profile.first_name}}</strong>
        {% endif %}
        <div class="container search-bar p-6">
            <form action="" class="d-flex pb-5" method="GET" id = "searchForm">
                <input class="form-control me-sm-2" type="search" name="search_query"  value="{{search_query}}" placeholder="Search Profiles"/>
                <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
            </form>
        </div>
    </div>
    <div class="container py-5">
        
        <div class="row row-cols-1 row-cols-md-2 row-cols-lg-3 g-4">
            {% for profile in profiles %}
            <div class="col">
                <div class="flip-card mx-auto">
                    <div class="flip-card-inner">
                        <div class="flip-card-front">
                            <img src="{{profile.profile_image.url}}" alt="Team Member" class="profile-img">
                            <h3>{{profile.first_name}} {{profile.last_name}}</h3>
                            <p>{{profile.short_intro|slice:"60"}}</p>
                            <p class="mt-3">
                                <span class="waving-hand">👋</span> Hover to know more!
                            </p>
                        </div>
                        <div class="flip-card-back">
                            <h3>About 
                                <a href="{% url 'user-profile' profile.userid %}">
                                <small>
                                    <strong>
                                        {{profile.first_name}} {{profile.last_name}}
                                    </strong>
                                </small>
                            </a>
                            </h3>
                            <p>{{profile.bio|slice:"150"}}</p>
                            <div class="social-icons mt-4">
                                <a href="#"><i class="fa fa-twitter"></i></a>
                                <a href="#"><i class="fa fa-linkedin"></i></a>
                                <a href="#"><i class="fa fa-github"></i></a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
            
        </div>
        <hr>
      </div>
      
      {% include "pagination.html" with queryset=profiles custom_range=custom_range %}
      
</main>
{% endblock content %}

devs/developers/users/templates/users/update_profile.html
{% extends "base.html" %}
{% block content %}
<form action="" method="POST">
    {% csrf_token %}
    {{form.as_p}}
    <input name="" id="" class="btn btn-primary" type="submit" value="Update"/>
    
</form>
{% endblock content %}